apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-website
  labels:
    app: portfolio-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      labels:
        app: portfolio-website
    spec:
      containers:
        - name: portfolio-website
          image: portfolio-website:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-website
  labels:
    app: portfolio-website
spec:
  type: NodePort
  selector:
    app: portfolio-website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
